version: '2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    volumes:
      - ./data:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g -Djava.net.preferIPv4Stack=true
    restart: always
    mem_limit: 4gb
    memswap_limit: 4gb
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    expose:
      - 5601
    ports:
      - 5601:5601
    links:
      - elastic:elasticsearch
    restart: always
  bitcoin:
    image: kylemanna/bitcoind:latest
    expose:
      - 8332
    ports:
      - 8332:8332
    volumes:
      - /data/.bitcoin:/bitcoin/.bitcoin
    restart: always
  fees:
    build: .
    restart: always
